name: flutter_example
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  hive_flutter: ^1.1.0
  get_it: ^7.6.8
  dio: ^5.4.2
  signals: ^4.5.1
  http: ^1.2.1
  go_router: ^13.2.3
  flutter_downloader: ^1.11.7
  path_provider: ^2.1.3
  permission_handler: ^11.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  hive_generator: ^2.0.1
  build_runner: ^2.4.8


flutter:
  uses-material-design: true